"""Canonical model-lane and provider-route metadata for adaptive orchestration."""

from __future__ import annotations

from copy import deepcopy
from datetime import date
from typing import Any

_ACTIVE_MODEL_VERSIONS: dict[str, str] = {
    "google/gemini-flash": "gemini-3-flash",
    "google/gemini-flash-lite": "gemini-3-flash-lite",
    "google/gemini-pro-high": "gemini-3.1-pro",
    "google/gemini-pro-low": "gemini-3.1-pro",
    "anthropic/opus-4.6": "claude-3-opus-20240229",
    "anthropic/sonnet-4.6": "claude-3-5-sonnet-20241022",
    "openai/gpt-4o": "gpt-4o",
    "deepseek/reasoner": "deepseek-reasoner",
    "deepseek/chat": "deepseek-chat",
}

_MODEL_VERSION_LABELS: dict[str, str] = {
    "google/gemini-flash": "Gemini 3 Flash",
    "google/gemini-flash-lite": "Gemini 3 Flash-Lite",
    "google/gemini-pro-high": "Gemini 3.1 Pro (High)",
    "google/gemini-pro-low": "Gemini 3.1 Pro (Low)",
    "anthropic/opus-4.6": "Claude 3 Opus",
    "anthropic/sonnet-4.6": "Claude 3.5 Sonnet",
    "openai/gpt-4o": "GPT-4o",
    "deepseek/reasoner": "DeepSeek R1 (Reasoner)",
    "deepseek/chat": "DeepSeek V3 (Chat)",
}


def get_active_model_id(canonical_id: str) -> str:
    """Return the currently preferred concrete model ID for a canonical lane."""
    return _ACTIVE_MODEL_VERSIONS.get(canonical_id, canonical_id.split("/")[-1])


def get_active_model_label(canonical_id: str) -> str:
    """Return the currently preferred human label for a canonical lane."""
    label = _MODEL_VERSION_LABELS.get(canonical_id)
    if label:
        return label
    return canonical_id.split("/")[-1].replace("-", " ").title()


_CANONICAL_MODEL_LANES: dict[str, dict[str, Any]] = {
    "anthropic/opus-4.6": {
        "family": "anthropic",
        "name": _MODEL_VERSION_LABELS["anthropic/opus-4.6"],
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
        "last_reviewed": "2026-03-22",
    },
    "anthropic/sonnet-4.6": {
        "family": "anthropic",
        "name": _MODEL_VERSION_LABELS["anthropic/sonnet-4.6"],
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "anthropic/haiku-4.5": {
        "family": "anthropic",
        "name": "fast",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "openai/gpt-4o-mini"],
        "last_reviewed": "2026-03-22",
    },
    "google/gemini-pro-high": {
        "family": "google",
        "name": _MODEL_VERSION_LABELS["google/gemini-pro-high"],
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-pro-low", "google/gemini-flash"],
        "last_reviewed": "2026-03-29",
    },
    "google/gemini-pro-low": {
        "family": "google",
        "name": _MODEL_VERSION_LABELS["google/gemini-pro-low"],
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-03-29",
    },
    "google/gemini-flash": {
        "family": "google",
        "name": _MODEL_VERSION_LABELS["google/gemini-flash"],
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash-lite", "deepseek/chat"],
        "last_reviewed": "2026-03-29",
    },
    "google/gemini-flash-lite": {
        "family": "google",
        "name": _MODEL_VERSION_LABELS["google/gemini-flash-lite"],
        "cluster": "budget-general",
        "benchmark_cluster": "budget-chat",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "low",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-4o": {
        "family": "openai",
        "name": _MODEL_VERSION_LABELS["openai/gpt-4o"],
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["openai/gpt-4o-mini", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-4o-mini": {
        "family": "openai",
        "name": "GPT-4o mini",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-03-22",
    },
    "openai/gpt-image-1": {
        "family": "openai",
        "name": "image",
        "cluster": "image-quality",
        "benchmark_cluster": "image-generation",
        "quality_tier": "premium",
        "reasoning_strength": "n/a",
        "context_strength": "n/a",
        "tool_strength": "n/a",
        "preferred_degrades": [],
        "last_reviewed": "2026-03-22",
    },
    "deepseek/reasoner": {
        "family": "deepseek",
        "name": _MODEL_VERSION_LABELS["deepseek/reasoner"],
        "cluster": "elite-reasoning",
        "benchmark_cluster": "reasoning-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["deepseek/chat", "google/gemini-pro-high"],
        "last_reviewed": "2026-03-22",
    },
    "deepseek/chat": {
        "family": "deepseek",
        "name": _MODEL_VERSION_LABELS["deepseek/chat"],
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "aggregator/openrouter-auto"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/openrouter-auto": {
        "family": "openrouter",
        "name": "router",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/kilo-glm5-free": {
        "family": "kilo",
        "name": "free",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "low",
        "preferred_degrades": ["aggregator/blackbox-grok-code-fast", "google/gemini-flash-lite"],
        "last_reviewed": "2026-03-22",
    },
    "aggregator/blackbox-grok-code-fast": {
        "family": "blackbox",
        "name": "free-burst",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "preferred_degrades": ["aggregator/kilo-glm5-free", "google/gemini-flash-lite"],
        "last_reviewed": "2026-03-22",
    },
    "mistral/mistral-large-latest": {
        "family": "mistral",
        "name": "Mistral Large",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-04-03",
    },
    "groq/llama-3.3-70b-versatile": {
        "family": "groq",
        "name": "Llama 3.3 70B",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "xai/grok-3": {
        "family": "xai",
        "name": "Grok 3",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-04-03",
    },
    "zai/glm-4.7": {
        "family": "zai",
        "name": "GLM 4.7",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-04-03",
    },
    "cerebras/llama3.3-70b": {
        "family": "cerebras",
        "name": "Llama 3.3 70B",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "opencode/claude-opus-4-6": {
        "family": "opencode",
        "name": "OpenCode Claude Opus",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
        "last_reviewed": "2026-04-03",
    },
    "huggingface/deepseek-ai/DeepSeek-R1": {
        "family": "huggingface",
        "name": "DeepSeek R1",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["deepseek/chat", "google/gemini-flash"],
        "last_reviewed": "2026-04-03",
    },
    "moonshot/kimi-k2.5": {
        "family": "moonshot",
        "name": "Kimi K2.5",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high"],
        "last_reviewed": "2026-04-03",
    },
    "ag/claude-opus-4-6-thinking": {
        "family": "google-antigravity",
        "name": "Opus 4.6 Thinking (Antigravity)",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["ag/claude-sonnet-4-6", "anthropic/sonnet-4.6", "openai/gpt-4o"],
        "last_reviewed": "2026-04-03",
    },
    "ag/claude-sonnet-4-6": {
        "family": "google-antigravity",
        "name": "Sonnet 4.6 (Antigravity)",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["ag/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
        "last_reviewed": "2026-04-03",
    },
    "ag/gemini-3.1-pro-high": {
        "family": "google-antigravity",
        "name": "Gemini 3.1 Pro High (Antigravity)",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["ag/gemini-3.1-pro-low", "google/gemini-pro-low", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "ag/gemini-3.1-pro-low": {
        "family": "google-antigravity",
        "name": "Gemini 3.1 Pro Low (Antigravity)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["ag/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "ag/gemini-3-flash": {
        "family": "google-antigravity",
        "name": "Gemini 3 Flash (Antigravity)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["ag/gpt-oss-120b-medium", "google/gemini-flash-lite", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "ag/gpt-oss-120b-medium": {
        "family": "google-antigravity",
        "name": "GPT OSS 120B Medium (Antigravity)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai/gpt-4o", "google/gemini-pro-high", "deepseek/reasoner"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-3-flash-preview": {
        "family": "google-gemini-cli",
        "name": "Gemini 3 Flash Preview (Gemini CLI)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["gc/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-3-pro-preview": {
        "family": "google-gemini-cli",
        "name": "Gemini 3 Pro Preview (Gemini CLI)",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["gc/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-3.1-pro-high": {
        "family": "google-gemini-cli",
        "name": "Gemini 3.1 Pro High (Gemini CLI)",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["gc/gemini-3.1-pro-low", "google/gemini-pro-low", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-3.1-pro-low": {
        "family": "google-gemini-cli",
        "name": "Gemini 3.1 Pro Low (Gemini CLI)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["gc/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-3-flash": {
        "family": "google-gemini-cli",
        "name": "Gemini 3 Flash (Gemini CLI)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["gc/gemini-2.5-flash", "google/gemini-flash-lite", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-2.5-pro": {
        "family": "google-gemini-cli",
        "name": "Gemini 2.5 Pro (Gemini CLI)",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["gc/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-2.5-flash": {
        "family": "google-gemini-cli",
        "name": "Gemini 2.5 Flash (Gemini CLI)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["gc/gemini-2.0-flash", "google/gemini-flash-lite", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "gc/gemini-2.0-flash": {
        "family": "google-gemini-cli",
        "name": "Gemini 2.0 Flash (Gemini CLI)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["google/gemini-flash-lite", "deepseek/chat", "anthropic/haiku-3.5"],
        "last_reviewed": "2026-04-03",
    },
    "qw/qwen3-coder-plus": {
        "family": "qwen-portal",
        "name": "Qwen3 Coder Plus (Qwen Portal)",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["qw/qwen3-coder-flash", "qw/coder-model", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "qw/qwen3-coder-flash": {
        "family": "qwen-portal",
        "name": "Qwen3 Coder Flash (Qwen Portal)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "preferred_degrades": ["qw/coder-model", "qw/vision-model", "google/gemini-flash"],
        "last_reviewed": "2026-04-03",
    },
    "qw/vision-model": {
        "family": "qwen-portal",
        "name": "Vision Model (Qwen Portal)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["qw/coder-model", "google/gemini-pro-low", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    "qw/coder-model": {
        "family": "qwen-portal",
        "name": "Coder Model (Qwen Portal)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["qw/vision-model", "google/gemini-pro-low", "deepseek/chat"],
        "last_reviewed": "2026-04-03",
    },
    # ── OpenAI Codex family (ChatGPT OAuth → chatgpt.com/backend-api/codex/responses) ──
    "openai-codex/gpt-5.4": {
        "family": "openai",
        "name": "Codex GPT-5.4",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.3-codex", "openai/gpt-4o"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex": {
        "family": "openai",
        "name": "Codex GPT-5.3",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini", "openai/gpt-4o"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex-xhigh": {
        "family": "openai",
        "name": "Codex GPT-5.3 xHigh",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.3-codex-high"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex-high": {
        "family": "openai",
        "name": "Codex GPT-5.3 High",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.3-codex"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex-low": {
        "family": "openai",
        "name": "Codex GPT-5.3 Low",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "low",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex-none": {
        "family": "openai",
        "name": "Codex GPT-5.3 None",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "none",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.3-codex-low"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.3-codex-spark": {
        "family": "openai",
        "name": "Codex GPT-5.3 Spark",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.1-codex-mini": {
        "family": "openai",
        "name": "Codex Mini",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["deepseek/chat", "google/gemini-flash"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.1-codex-mini-high": {
        "family": "openai",
        "name": "Codex Mini High",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.2-codex": {
        "family": "openai",
        "name": "Codex GPT-5.2",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.2": {
        "family": "openai",
        "name": "GPT-5.2",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.2-codex"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.1-codex-max": {
        "family": "openai",
        "name": "Codex GPT-5.1 Max",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.1-codex": {
        "family": "openai",
        "name": "Codex GPT-5.1",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5.1": {
        "family": "openai",
        "name": "GPT-5.1",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5-codex": {
        "family": "openai",
        "name": "Codex GPT-5",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-5-codex-mini": {
        "family": "openai",
        "name": "Codex GPT-5 Mini",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/codex-mini": {
        "family": "openai",
        "name": "Codex Mini (alias)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/o4-mini": {
        "family": "openai",
        "name": "o4-mini (Codex)",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "preferred_degrades": ["openai-codex/gpt-5.1-codex-mini"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-4.1": {
        "family": "openai",
        "name": "GPT-4.1 (Codex)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["openai/gpt-4o"],
        "last_reviewed": "2026-04-07",
    },
    "openai-codex/gpt-4o": {
        "family": "openai",
        "name": "GPT-4o (Codex)",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "high",
        "preferred_degrades": ["openai/gpt-4o"],
        "last_reviewed": "2026-04-07",
    },
}

_PROVIDER_LANE_BINDINGS: dict[str, dict[str, Any]] = {
    "anthropic-claude": {
        "family": "anthropic",
        "name": "quality",
        "canonical_model": "anthropic/opus-4.6",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "anthropic/opus-4.6",
        "degrade_to": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
    },
    "deepseek-chat": {
        "family": "deepseek",
        "name": "workhorse",
        "canonical_model": "deepseek/chat",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "deepseek/chat",
        "degrade_to": ["google/gemini-flash", "aggregator/openrouter-auto"],
    },
    "deepseek-reasoner": {
        "family": "deepseek",
        "name": "reasoning",
        "canonical_model": "deepseek/reasoner",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "reasoning-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "deepseek/reasoner",
        "degrade_to": ["deepseek/chat", "google/gemini-pro-high"],
    },
    "gemini-flash": {
        "family": "google",
        "name": "fast",
        "canonical_model": "google/gemini-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "google/gemini-flash",
        "degrade_to": ["google/gemini-flash-lite", "deepseek/chat"],
    },
    "gemini-flash-lite": {
        "family": "google",
        "name": "cheap",
        "canonical_model": "google/gemini-flash-lite",
        "route_type": "direct",
        "cluster": "budget-general",
        "benchmark_cluster": "budget-chat",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "low",
        "same_model_group": "google/gemini-flash-lite",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
    "openai-gpt4o": {
        "family": "openai",
        "name": "balanced",
        "canonical_model": "openai/gpt-4o",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "openai/gpt-4o",
        "degrade_to": ["openai/gpt-4o-mini", "google/gemini-pro-high"],
    },
    "openai-images": {
        "family": "openai",
        "name": "image",
        "canonical_model": "openai/gpt-image-1",
        "route_type": "direct",
        "cluster": "image-quality",
        "benchmark_cluster": "image-generation",
        "quality_tier": "premium",
        "reasoning_strength": "n/a",
        "context_strength": "n/a",
        "tool_strength": "n/a",
        "same_model_group": "openai/gpt-image-1",
        "degrade_to": [],
    },
    "openrouter-fallback": {
        "family": "openrouter",
        "name": "router",
        "canonical_model": "aggregator/openrouter-auto",
        "route_type": "aggregator",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "same_model_group": "aggregator/openrouter-auto",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
    "kilocode": {
        "family": "kilo",
        "name": "free",
        "canonical_model": "aggregator/kilo-glm5-free",
        "route_type": "aggregator",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "low",
        "same_model_group": "aggregator/kilo-glm5-free",
        "degrade_to": ["aggregator/blackbox-grok-code-fast", "google/gemini-flash-lite"],
    },
    "kilo-sonnet": {
        "family": "kilo",
        "name": "sonnet",
        "canonical_model": "anthropic/sonnet-4.6",
        "route_type": "aggregator",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "anthropic/sonnet-4.6",
        "degrade_to": ["anthropic/haiku-4.5", "deepseek/chat", "google/gemini-flash"],
    },
    "kilo-opus": {
        "family": "kilo",
        "name": "opus",
        "canonical_model": "anthropic/opus-4.6",
        "route_type": "aggregator",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "anthropic/opus-4.6",
        "degrade_to": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
    },
    "blackbox-free": {
        "family": "blackbox",
        "name": "burst",
        "canonical_model": "aggregator/blackbox-grok-code-fast",
        "route_type": "aggregator",
        "cluster": "budget-general",
        "benchmark_cluster": "budget-chat",
        "quality_tier": "budget",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "mid",
        "same_model_group": "aggregator/blackbox-grok-code-fast",
        "degrade_to": ["aggregator/kilo-glm5-free", "google/gemini-flash-lite"],
    },
    "clawrouter": {
        "family": "blockrun",
        "name": "wallet-router",
        "canonical_model": "aggregator/openrouter-auto",
        "route_type": "wallet-router",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "same_model_group": "aggregator/openrouter-auto",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
    "kilo-auto-frontier": {
        "family": "kilo",
        "name": "frontier",
        "canonical_model": "anthropic/opus-4.6",
        "route_type": "aggregator",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "anthropic/opus-4.6",
        "degrade_to": ["kilo-sonnet", "openai/gpt-4o", "deepseek/reasoner"],
    },
    "kilo-auto-balanced": {
        "family": "kilo",
        "name": "balanced",
        "canonical_model": "anthropic/sonnet-4.6",
        "route_type": "aggregator",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "anthropic/sonnet-4.6",
        "degrade_to": ["google/gemini-pro-high", "deepseek/chat"],
    },
    "kilo-auto-free": {
        "family": "kilo",
        "name": "free",
        "canonical_model": "aggregator/kilo-glm5-free",
        "route_type": "aggregator",
        "cluster": "budget-general",
        "benchmark_cluster": "free-coding",
        "quality_tier": "free",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "low",
        "same_model_group": "aggregator/kilo-glm5-free",
        "degrade_to": ["aggregator/blackbox-grok-code-fast", "google/gemini-flash-lite"],
    },
    "mistral": {
        "family": "mistral",
        "name": "quality",
        "canonical_model": "mistral/mistral-large-latest",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "mistral/mistral-large-latest",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "groq": {
        "family": "groq",
        "name": "fast",
        "canonical_model": "groq/llama-3.3-70b-versatile",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "groq/llama-3.3-70b-versatile",
        "degrade_to": ["google/gemini-flash", "deepseek/chat"],
    },
    "xai": {
        "family": "xai",
        "name": "quality",
        "canonical_model": "xai/grok-3",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "xai/grok-3",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "zai": {
        "family": "zai",
        "name": "quality",
        "canonical_model": "zai/glm-4.7",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "zai/glm-4.7",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "cerebras": {
        "family": "cerebras",
        "name": "fast",
        "canonical_model": "cerebras/llama3.3-70b",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "cerebras/llama3.3-70b",
        "degrade_to": ["google/gemini-flash", "deepseek/chat"],
    },
    "opencode": {
        "family": "opencode",
        "name": "quality",
        "canonical_model": "opencode/claude-opus-4-6",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "opencode/claude-opus-4-6",
        "degrade_to": ["anthropic/sonnet-4.6", "openai/gpt-4o", "deepseek/reasoner"],
    },
    "huggingface": {
        "family": "huggingface",
        "name": "workhorse",
        "canonical_model": "huggingface/deepseek-ai/DeepSeek-R1",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "huggingface/deepseek-ai/DeepSeek-R1",
        "degrade_to": ["deepseek/chat", "google/gemini-flash"],
    },
    "moonshot": {
        "family": "moonshot",
        "name": "quality",
        "canonical_model": "moonshot/kimi-k2.5",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "moonshot/kimi-k2.5",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "minimax": {
        "family": "minimax",
        "name": "quality",
        "canonical_model": "minimax/MiniMax-M2.7",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "minimax/MiniMax-M2.7",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "volcengine": {
        "family": "volcengine",
        "name": "quality",
        "canonical_model": "volcengine/doubao-seed-1-8-251228",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "volcengine/doubao-seed-1-8-251228",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "byteplus": {
        "family": "byteplus",
        "name": "quality",
        "canonical_model": "byteplus/seed-1-8-251228",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "byteplus/seed-1-8-251228",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "qwen": {
        "family": "qwen",
        "name": "quality",
        "canonical_model": "qwen/qwen3.6-plus",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "qwen/qwen3.6-plus",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "openai-codex": {
        "family": "openai",
        "name": "codex",
        "canonical_model": "openai-codex/gpt-5.4",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.4",
        "degrade_to": ["openai-codex-mini", "openai-codex-spark"],
    },
    "openai-codex-mini": {
        "family": "openai",
        "name": "codex-mini",
        "canonical_model": "openai-codex/gpt-5.1-codex-mini",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.1-codex-mini",
        "degrade_to": ["deepseek/chat", "google/gemini-flash"],
    },
    "openai-codex-spark": {
        "family": "openai",
        "name": "codex-spark",
        "canonical_model": "openai-codex/gpt-5.3-codex-spark",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.3-codex-spark",
        "degrade_to": ["openai-codex-mini", "deepseek/chat"],
    },
    "openai-codex-high": {
        "family": "openai",
        "name": "codex-high",
        "canonical_model": "openai-codex/gpt-5.3-codex-high",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.3-codex-high",
        "degrade_to": ["openai-codex", "openai-codex-mini"],
    },
    "openai-codex-xhigh": {
        "family": "openai",
        "name": "codex-xhigh",
        "canonical_model": "openai-codex/gpt-5.3-codex-xhigh",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.3-codex-xhigh",
        "degrade_to": ["openai-codex-high", "openai-codex"],
    },
    "openai-codex-low": {
        "family": "openai",
        "name": "codex-low",
        "canonical_model": "openai-codex/gpt-5.3-codex-low",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-coding",
        "quality_tier": "mid",
        "reasoning_strength": "low",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "openai-codex/gpt-5.3-codex-low",
        "degrade_to": ["openai-codex-mini", "openai-codex-spark"],
    },
    "claude-code": {
        "family": "anthropic",
        "name": "code",
        "canonical_model": "claude-code",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "claude-code",
        "degrade_to": ["anthropic/sonnet-4.6", "openai/gpt-4o"],
    },
    "google-antigravity-opus": {
        "family": "google-antigravity",
        "name": "opus",
        "canonical_model": "ag/claude-opus-4-6-thinking",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "ag/claude-opus-4-6-thinking",
        "degrade_to": ["ag/claude-sonnet-4-6", "anthropic/sonnet-4.6", "openai/gpt-4o"],
    },
    "google-antigravity-sonnet": {
        "family": "google-antigravity",
        "name": "sonnet",
        "canonical_model": "ag/claude-sonnet-4-6",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "ag/claude-sonnet-4-6",
        "degrade_to": ["ag/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
    },
    "google-antigravity-gemini-pro-high": {
        "family": "google-antigravity",
        "name": "gemini-pro-high",
        "canonical_model": "ag/gemini-3.1-pro-high",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "ag/gemini-3.1-pro-high",
        "degrade_to": ["ag/gemini-3.1-pro-low", "google/gemini-pro-low", "deepseek/chat"],
    },
    "google-antigravity-gemini-pro-low": {
        "family": "google-antigravity",
        "name": "gemini-pro-low",
        "canonical_model": "ag/gemini-3.1-pro-low",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "ag/gemini-3.1-pro-low",
        "degrade_to": ["ag/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
    },
    "google-antigravity-gemini-flash": {
        "family": "google-antigravity",
        "name": "gemini-flash",
        "canonical_model": "ag/gemini-3-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "ag/gemini-3-flash",
        "degrade_to": ["ag/gpt-oss-120b-medium", "google/gemini-flash-lite", "deepseek/chat"],
    },
    "google-antigravity-gpt-oss-120b-medium": {
        "family": "google-antigravity",
        "name": "gpt-oss-120b-medium",
        "canonical_model": "ag/gpt-oss-120b-medium",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "ag/gpt-oss-120b-medium",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high", "deepseek/reasoner"],
    },
    "google-gemini-cli-flash-preview": {
        "family": "google-gemini-cli",
        "name": "flash-preview",
        "canonical_model": "gc/gemini-3-flash-preview",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "gc/gemini-3-flash-preview",
        "degrade_to": ["gc/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
    },
    "google-gemini-cli-pro-preview": {
        "family": "google-gemini-cli",
        "name": "pro-preview",
        "canonical_model": "gc/gemini-3-pro-preview",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "gc/gemini-3-pro-preview",
        "degrade_to": ["gc/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
    },
    "google-gemini-cli-pro-high": {
        "family": "google-gemini-cli",
        "name": "pro-high",
        "canonical_model": "gc/gemini-3.1-pro-high",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "gc/gemini-3.1-pro-high",
        "degrade_to": ["gc/gemini-3.1-pro-low", "google/gemini-pro-low", "deepseek/chat"],
    },
    "google-gemini-cli-pro-low": {
        "family": "google-gemini-cli",
        "name": "pro-low",
        "canonical_model": "gc/gemini-3.1-pro-low",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "gc/gemini-3.1-pro-low",
        "degrade_to": ["gc/gemini-3-flash", "google/gemini-flash", "deepseek/chat"],
    },
    "google-gemini-cli-flash": {
        "family": "google-gemini-cli",
        "name": "flash",
        "canonical_model": "gc/gemini-3-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "gc/gemini-3-flash",
        "degrade_to": ["gc/gemini-2.5-flash", "google/gemini-flash-lite", "deepseek/chat"],
    },
    "google-gemini-cli-2-5-pro": {
        "family": "google-gemini-cli",
        "name": "2-5-pro",
        "canonical_model": "gc/gemini-2.5-pro",
        "route_type": "direct",
        "cluster": "elite-reasoning",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "premium",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "gc/gemini-2.5-pro",
        "degrade_to": ["gc/gemini-3.1-pro-high", "google/gemini-pro-high", "deepseek/reasoner"],
    },
    "google-gemini-cli-2-5-flash": {
        "family": "google-gemini-cli",
        "name": "2-5-flash",
        "canonical_model": "gc/gemini-2.5-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "gc/gemini-2.5-flash",
        "degrade_to": ["gc/gemini-2.0-flash", "google/gemini-flash-lite", "deepseek/chat"],
    },
    "google-gemini-cli-2-0-flash": {
        "family": "google-gemini-cli",
        "name": "2-0-flash",
        "canonical_model": "gc/gemini-2.0-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "budget",
        "reasoning_strength": "low",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "gc/gemini-2.0-flash",
        "degrade_to": ["google/gemini-flash-lite", "deepseek/chat", "anthropic/haiku-3.5"],
    },
    "qwen-portal-coder-plus": {
        "family": "qwen-portal",
        "name": "coder-plus",
        "canonical_model": "qw/qwen3-coder-plus",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "qw/qwen3-coder-plus",
        "degrade_to": ["qw/qwen3-coder-flash", "qw/coder-model", "deepseek/chat"],
    },
    "qwen-portal-coder-flash": {
        "family": "qwen-portal",
        "name": "coder-flash",
        "canonical_model": "qw/qwen3-coder-flash",
        "route_type": "direct",
        "cluster": "fast-workhorse",
        "benchmark_cluster": "fast-general",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "qw/qwen3-coder-flash",
        "degrade_to": ["qw/coder-model", "qw/vision-model", "google/gemini-flash"],
    },
    "qwen-portal-vision": {
        "family": "qwen-portal",
        "name": "vision",
        "canonical_model": "qw/vision-model",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "qw/vision-model",
        "degrade_to": ["qw/coder-model", "google/gemini-pro-low", "deepseek/chat"],
    },
    "qwen-portal-coder": {
        "family": "qwen-portal",
        "name": "coder",
        "canonical_model": "qw/coder-model",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "mid",
        "context_strength": "high",
        "tool_strength": "high",
        "same_model_group": "qw/coder-model",
        "degrade_to": ["qw/vision-model", "google/gemini-pro-low", "deepseek/chat"],
    },
    "github-copilot": {
        "family": "github",
        "name": "copilot",
        "canonical_model": "github-copilot/gpt-4o",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "github-copilot/gpt-4o",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "synthetic": {
        "family": "synthetic",
        "name": "workhorse",
        "canonical_model": "synthetic/hf:MiniMaxAI/MiniMax-M2.1",
        "route_type": "direct",
        "cluster": "balanced-workhorse",
        "benchmark_cluster": "balanced-coding",
        "quality_tier": "mid",
        "reasoning_strength": "high",
        "context_strength": "mid",
        "tool_strength": "medium",
        "same_model_group": "synthetic/hf:MiniMaxAI/MiniMax-M2.1",
        "degrade_to": ["deepseek/chat", "google/gemini-flash"],
    },
    "kimi-coding": {
        "family": "moonshot",
        "name": "coding",
        "canonical_model": "kimi-coding/k2p5",
        "route_type": "direct",
        "cluster": "quality-workhorse",
        "benchmark_cluster": "quality-coding",
        "quality_tier": "high",
        "reasoning_strength": "high",
        "context_strength": "high",
        "tool_strength": "medium",
        "same_model_group": "kimi-coding/k2p5",
        "degrade_to": ["openai/gpt-4o", "google/gemini-pro-high"],
    },
    "vercel-ai-gateway": {
        "family": "vercel",
        "name": "gateway",
        "canonical_model": "vercel-ai-gateway/anthropic/claude-opus-4.6",
        "route_type": "aggregator",
        "cluster": "aggregator-fallback",
        "benchmark_cluster": "marketplace-general",
        "quality_tier": "variable",
        "reasoning_strength": "variable",
        "context_strength": "variable",
        "tool_strength": "variable",
        "same_model_group": "vercel-ai-gateway/anthropic/claude-opus-4.6",
        "degrade_to": ["aggregator/kilo-glm5-free", "aggregator/blackbox-grok-code-fast"],
    },
}


def _freshness_state_from_review(last_reviewed: str) -> dict[str, Any]:
    reviewed = str(last_reviewed or "").strip()
    if not reviewed:
        return {
            "last_reviewed": "",
            "review_age_days": -1,
            "freshness_status": "unknown",
            "freshness_hint": "review date not recorded",
        }

    reviewed_on = date.fromisoformat(reviewed)
    age_days = max(0, (date.today() - reviewed_on).days)
    if age_days <= 7:
        status = "fresh"
        hint = "benchmark and cost assumptions were reviewed recently"
    elif age_days <= 21:
        status = "aging"
        hint = "benchmark and cost assumptions are aging and worth rechecking soon"
    else:
        status = "stale"
        hint = "benchmark and cost assumptions are stale; review before trusting them heavily"
    return {
        "last_reviewed": reviewed,
        "review_age_days": age_days,
        "freshness_status": status,
        "freshness_hint": hint,
    }


def _lane_binding_with_freshness(binding: dict[str, Any]) -> dict[str, Any]:
    lane = deepcopy(binding)
    canonical_model = str(lane.get("canonical_model") or "")
    canonical = _CANONICAL_MODEL_LANES.get(canonical_model, {})
    freshness = _freshness_state_from_review(str(canonical.get("last_reviewed") or ""))
    lane.update(
        {
            "last_reviewed": freshness["last_reviewed"],
            "review_age_days": freshness["review_age_days"],
            "freshness_status": freshness["freshness_status"],
            "freshness_hint": freshness["freshness_hint"],
        }
    )
    return lane


_DEFAULT_TRANSPORT_BY_BACKEND: dict[str, dict[str, Any]] = {
    "openai-compat": {
        "profile": "openai-compatible",
        "compatibility": "native",
        "probe_confidence": "high",
        "auth_mode": "bearer",
        "probe_strategy": "models",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "/models",
        "chat_path": "/chat/completions",
        "image_generation_path": "/images/generations",
        "image_edit_path": "/images/edits",
        "requires_api_key": True,
        "supports_models_probe": True,
        "notes": [],
    },
    "anthropic-compat": {
        "profile": "anthropic-compatible",
        "compatibility": "native",
        "probe_confidence": "high",
        "auth_mode": "bearer",
        "probe_strategy": "models",
        "probe_payload_kind": "anthropic-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "/models",
        "chat_path": "/chat/completions",
        "image_generation_path": "/images/generations",
        "image_edit_path": "/images/edits",
        "requires_api_key": True,
        "supports_models_probe": True,
        "notes": [],
    },
    "google-genai": {
        "profile": "google-genai",
        "compatibility": "native",
        "probe_confidence": "medium",
        "auth_mode": "query",
        "probe_strategy": "none",
        "probe_payload_kind": "google-generate-content",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": True,
        "supports_models_probe": False,
        "notes": ["genai backend uses generateContent instead of OpenAI-compatible chat paths"],
    },
    "oauth": {
        "profile": "oauth-openai-compat",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["OAuth-wrapped backend; token injected at request time via faigate-auth helper"],
    },
}

_PROVIDER_TRANSPORT_BINDINGS: dict[str, dict[str, Any]] = {
    "openrouter-fallback": {
        "profile": "openrouter-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "high",
        "auth_mode": "bearer",
        "probe_strategy": "models_or_chat",
        "probe_payload_kind": "openrouter-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "/models",
        "chat_path": "/chat/completions",
        "notes": [
            "requires HTTP-Referer and X-Title headers for best marketplace attribution",
            "route remains OpenAI-compatible but upstream model selection is marketplace-managed",
            "falls back to a shallow chat probe when the models route is not reliable enough",
        ],
    },
    "kilocode": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "free-tier model availability and path behavior should be revalidated regularly",
        ],
    },
    "kilo-sonnet": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "paid Kilo routes should be revalidated against current gateway behavior periodically",
        ],
    },
    "kilo-opus": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "paid Kilo routes should be revalidated against current gateway behavior periodically",
        ],
    },
    "blackbox-free": {
        "profile": "blackbox-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "blackbox-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            ("low-cost BLACKBOX routes can shift quickly in pricing, auth behavior, or model availability"),
        ],
    },
    "kilo-auto-frontier": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "paid Kilo routes should be revalidated against current gateway behavior periodically",
        ],
    },
    "kilo-auto-balanced": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "paid Kilo routes should be revalidated against current gateway behavior periodically",
        ],
    },
    "kilo-auto-free": {
        "profile": "kilo-openai-compat",
        "compatibility": "aggregator",
        "probe_confidence": "medium",
        "auth_mode": "bearer",
        "probe_strategy": "chat",
        "probe_payload_kind": "kilo-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "/chat/completions",
        "supports_models_probe": False,
        "notes": [
            "aggregator route uses a shallow chat probe instead of assuming /models support",
            "free-tier model availability and path behavior should be revalidated regularly",
        ],
    },
    # Codex providers: base_url IS the full endpoint; chat_path must be "" to avoid
    # appending /chat/completions → chatgpt.com/backend-api/codex/responses/chat/completions
    "openai-codex": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": [
            "Codex endpoint is the full URL; no /chat/completions suffix",
            "OAuth token injected by OAuthBackend from ~/.codex/auth.json",
        ],
    },
    "openai-codex-mini": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["Codex mini endpoint; no /chat/completions suffix"],
    },
    "openai-codex-spark": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["Codex spark endpoint; no /chat/completions suffix"],
    },
    "openai-codex-high": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["Codex high endpoint; no /chat/completions suffix"],
    },
    "openai-codex-xhigh": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["Codex xhigh endpoint; no /chat/completions suffix"],
    },
    "openai-codex-low": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "probe_payload_kind": "openai-chat-minimal",
        "probe_payload_text": "ping",
        "probe_payload_max_tokens": 1,
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["Codex low reasoning endpoint; no /chat/completions suffix"],
    },
    # GPT-5.4 reasoning-effort variants (extra_body injection via provider config)
    "openai-codex-5.4-xhigh": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["GPT-5.4 extra_high reasoning via reasoning_effort=extra_high in body"],
    },
    "openai-codex-5.4-high": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["GPT-5.4 high reasoning via reasoning_effort=high in body"],
    },
    "openai-codex-5.4-medium": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["GPT-5.4 medium reasoning via reasoning_effort=medium in body"],
    },
    "openai-codex-5.4-low": {
        "profile": "oauth-codex",
        "compatibility": "native",
        "probe_confidence": "low",
        "auth_mode": "bearer",
        "probe_strategy": "none",
        "models_path": "",
        "chat_path": "",
        "image_generation_path": "",
        "image_edit_path": "",
        "requires_api_key": False,
        "supports_models_probe": False,
        "notes": ["GPT-5.4 low reasoning via reasoning_effort=low in body"],
    },
}

_CANONICAL_MODEL_ROUTE_REGISTRY: dict[str, list[dict[str, Any]]] = {
    "anthropic/opus-4.6": [
        {
            "route_id": "anthropic-direct/opus-4.6",
            "provider_name": "anthropic-claude",
            "provider_family": "anthropic",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/anthropic-opus-4.6",
            "provider_name": "openrouter-anthropic-opus",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
        {
            "route_id": "kilocode/anthropic-opus-4.6",
            "provider_name": "kilo-opus",
            "provider_family": "kilo",
            "route_type": "aggregator",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "blackbox/anthropic-opus-4.6",
            "provider_name": "blackbox-anthropic-opus",
            "provider_family": "blackbox",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
    ],
    "anthropic/sonnet-4.6": [
        {
            "route_id": "anthropic-direct/sonnet-4.6",
            "provider_name": "anthropic-sonnet",
            "provider_family": "anthropic",
            "route_type": "direct",
            "availability": "catalog",
            "route_group": "same-lane",
        },
        {
            "route_id": "kilocode/anthropic-sonnet-4.6",
            "provider_name": "kilo-sonnet",
            "provider_family": "kilo",
            "route_type": "aggregator",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/anthropic-sonnet-4.6",
            "provider_name": "openrouter-anthropic-sonnet",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
    ],
    "openai/gpt-4o": [
        {
            "route_id": "openai-direct/gpt-4o",
            "provider_name": "openai-gpt4o",
            "provider_family": "openai",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/openai-gpt-4o",
            "provider_name": "openrouter-openai-gpt4o",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
    ],
    "deepseek/reasoner": [
        {
            "route_id": "deepseek-direct/reasoner",
            "provider_name": "deepseek-reasoner",
            "provider_family": "deepseek",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/deepseek-reasoner",
            "provider_name": "openrouter-deepseek-reasoner",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
    ],
    "deepseek/chat": [
        {
            "route_id": "deepseek-direct/chat",
            "provider_name": "deepseek-chat",
            "provider_family": "deepseek",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/deepseek-chat",
            "provider_name": "openrouter-fallback",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "configured",
            "route_group": "same-lane",
        },
    ],
    "google/gemini-flash": [
        {
            "route_id": "google-direct/gemini-flash",
            "provider_name": "gemini-flash",
            "provider_family": "google",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "openrouter/gemini-flash",
            "provider_name": "openrouter-gemini-flash",
            "provider_family": "openrouter",
            "route_type": "aggregator",
            "availability": "catalog",
            "route_group": "same-lane",
        },
    ],
    "google/gemini-flash-lite": [
        {
            "route_id": "google-direct/gemini-flash-lite",
            "provider_name": "gemini-flash-lite",
            "provider_family": "google",
            "route_type": "direct",
            "availability": "configured",
            "route_group": "same-lane",
        },
        {
            "route_id": "kilocode/glm-5-free",
            "provider_name": "kilocode",
            "provider_family": "kilo",
            "route_type": "aggregator",
            "availability": "configured",
            "route_group": "cluster-alternative",
        },
        {
            "route_id": "blackbox/grok-code-fast",
            "provider_name": "blackbox-free",
            "provider_family": "blackbox",
            "route_type": "aggregator",
            "availability": "configured",
            "route_group": "cluster-alternative",
        },
    ],
}


def get_canonical_model_catalog() -> dict[str, dict[str, Any]]:
    """Return the canonical model-lane catalog."""
    payload: dict[str, dict[str, Any]] = {}
    for canonical_model, item in _CANONICAL_MODEL_LANES.items():
        payload[canonical_model] = {
            **deepcopy(item),
            **_freshness_state_from_review(str(item.get("last_reviewed") or "")),
        }
    return payload


def get_provider_lane_binding(provider_name: str) -> dict[str, Any]:
    """Return lane metadata for one configured provider or route."""
    binding = _PROVIDER_LANE_BINDINGS.get(provider_name, {})
    if not binding:
        return {}
    return _lane_binding_with_freshness(binding)


def get_provider_transport_binding(
    provider_name: str,
    *,
    backend: str = "openai-compat",
    contract: str = "generic",
) -> dict[str, Any]:
    """Return normalized transport defaults for one provider backend/route."""
    binding = deepcopy(_DEFAULT_TRANSPORT_BY_BACKEND.get(backend, {}))
    if contract == "local-worker":
        binding["requires_api_key"] = False
    binding.update(deepcopy(_PROVIDER_TRANSPORT_BINDINGS.get(provider_name, {})))
    return binding


def get_canonical_model_routes(canonical_model: str) -> list[dict[str, Any]]:
    """Return known direct and aggregator execution routes for one canonical model."""
    routes = _CANONICAL_MODEL_ROUTE_REGISTRY.get(canonical_model, [])
    return deepcopy(routes)


def _route_setup_provider_name(provider_name: str, provider_family: str) -> str:
    if provider_name in _PROVIDER_LANE_BINDINGS:
        return provider_name
    family = str(provider_family or "").strip().lower()
    if family == "openrouter":
        return "openrouter-fallback"
    if family == "kilo":
        return "kilocode"
    if family == "blackbox":
        return "blackbox-free"
    return provider_name


def get_route_add_recommendations(
    *,
    configured_provider_names: set[str] | list[str] | tuple[str, ...],
    canonical_model: str = "",
    degrade_to: list[str] | tuple[str, ...] | None = None,
    family: str = "",
) -> list[dict[str, Any]]:
    """Return concrete provider additions that would improve route resilience.

    Recommendations are ordered by usefulness:
    1. same-lane mirrors for the exact canonical model
    2. next-cluster providers from the configured degrade chain
    3. remaining family siblings that are known in the catalog
    """

    configured = {str(name) for name in configured_provider_names if str(name)}
    seen = set(configured)
    recommendations: list[dict[str, Any]] = []

    def add_route_candidates(target_model: str, strategy: str) -> None:
        for route in get_canonical_model_routes(target_model):
            provider_name = str(route.get("provider_name") or "")
            if not provider_name or provider_name in seen:
                continue
            if strategy == "same-lane-add":
                reason = f"adds a same-lane mirror for {target_model}"
            else:
                reason = f"adds a cluster fallback for {target_model}"
            recommendations.append(
                {
                    "provider_name": provider_name,
                    "setup_provider_name": _route_setup_provider_name(
                        provider_name,
                        str(route.get("provider_family") or ""),
                    ),
                    "strategy": strategy,
                    "strategy_label": {
                        "same-lane-add": "same lane",
                        "cluster-add": "next cluster lane",
                        "family-add": "family lane",
                    }.get(strategy, "route addition"),
                    "canonical_model": target_model,
                    "provider_family": str(route.get("provider_family") or ""),
                    "route_type": str(route.get("route_type") or ""),
                    "route_group": str(route.get("route_group") or ""),
                    "reason": reason,
                }
            )
            seen.add(provider_name)

    if canonical_model:
        add_route_candidates(canonical_model, "same-lane-add")

    for target_model in degrade_to or []:
        if str(target_model):
            add_route_candidates(str(target_model), "cluster-add")

    if family:
        for provider_name, binding in sorted(_PROVIDER_LANE_BINDINGS.items()):
            if provider_name in seen:
                continue
            if str(binding.get("family") or "") != family:
                continue
            recommendations.append(
                {
                    "provider_name": provider_name,
                    "setup_provider_name": provider_name,
                    "strategy": "family-add",
                    "strategy_label": "family lane",
                    "canonical_model": str(binding.get("canonical_model") or ""),
                    "provider_family": family,
                    "route_type": str(binding.get("route_type") or ""),
                    "route_group": "family-lane",
                    "reason": (f"adds another {family} family lane for recovery and routing flexibility"),
                }
            )
            seen.add(provider_name)

    return recommendations
